defaults: &defaults
  options:
    raise_not_found_error: false
    use_utc: true
development:
  <<: *defaults
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: once_development
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017

test:
  <<: *defaults
  sessions:
    default:
      database: once_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
production:
  <<: *defaults
  sessions:
    default:
      hosts: 
        - <%= ENV['MONGOID_PRIMARY_HOST_PORT'] %>
      database: <%= ENV['MONGOID_DATABASE'] %>
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      options:
        consistency: :strong
        safe: false
